### ISSUE TITLE
Bug: Occasional incorrect indentation of XML when sync'd from CRX w/o formatting

### ISSUE THREAD

**Issue by HitmanInWis** [aemide/issue-tracker#1]
I am configured to NOT reformat files after Content Sync, but I AM configured to clean up invalid fields.  I believe the clean up function is  what's bugged to leave invalid indentation.

An example is as follows:

```
<jcr:root xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:dam="http://www.day.com/dam/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="nt:file">
    <jcr:content
        jcr:lastModifiedBy="admin"
        jcr:mixinTypes="[dam:Thumbnails]"
        jcr:primaryType="nt:resource"/>
</jcr:root>
```

becomes

```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:dam="http://www.day.com/dam/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="nt:file">
    <jcr:content
            jcr:mixinTypes="[dam:Thumbnails]"
        jcr:primaryType="nt:resource"/>
</jcr:root>
```

**Comment by HitmanInWis** [comment]
after another month or so of working, I've not seen any issue with the workaround @karollewandowski .  If there's no way to really solve this issue effectively w/o the user changing their IDE settings (i.e. the workaround) I'm cool closing out this item as "wont fix".

**Comment by karollewandowski** [comment]
Thank you for the update. Unfortunately, I don't see any good option for fixing it in the plugin.
I'm closing the issue then.

Thank you again for your time.
