### ISSUE TITLE
filter.xml mode "update_properties" not known

### ISSUE THREAD

**Issue by LucaNerlich** [aemide/issue-tracker#9]
Hi,

when using "update_properties" the AEM IDE Plugin does not recognize it as an allowed "mode" value.
It however suggest to use "update" instead, which is deprecated.

https://jackrabbit.apache.org/filevault/filter.html#filter-elements

![image](https://github.com/user-attachments/assets/90c4bf6d-77bf-485e-b7f0-f7936ada26d3)

![image](https://github.com/user-attachments/assets/06aaf2c0-437f-4aa3-a91b-3dea0f4efab1)

**Comment by karollewandowski** [comment]
Hi, thank you for reporting this.
It has been implemented and is available in the [EAP](https://plugins.jetbrains.com/plugin/9269-aem-ide/docs/early-access-program.html) version until the stable version is released.
